### PR TITLE
Support for tvOS.

### PR DESCRIPTION
**Pull request by arturgrigor**

### CODE REVIEW

**Comment by skywinder** [comment]
Thank you for your pull request. 
Did you check, how it workd on tvOS? 
Can you add some example to the project as well to make it clear?

**Comment by arturgrigor** [comment]
Yes, I did. I've been using it for a couple of months in this app (https://itunes.apple.com/us/app/cassette-your-favorite-music/id1180322622?mt=8) and there are no problems so far.

**Comment by skywinder** [comment]
Glad to hear it, thanks! 👍  Great app, bdw!

**Comment by arturgrigor** [comment]
Thanks! 🙂

**Pull request merged**
