### PR TITLE
Added rate animations

### PR DESCRIPTION
**Pull request by dpelletier2017**
Basically everything happens in : 
- Gauge+Animations.swift (new file)
- MainViewController.swift (changed)

And I had to add two variables : 
- animationTimer
- animationCompletionBlock

Now, I absolutely DON'T get the easy part of the job, shame on me... I don't get how to update the framework in the example. So the example won't compile for now. I was not able to test the final result, but it should work no problem.

### CODE REVIEW

**Comment by skywinder** [comment]
@f8th wow. Looks nice! I will add your PR soon! 
I didn't find  easier way to animate `UIView`'s yet.
Probably it's possible, by going to Core Animation. So will add your method.
Thank you for contribution!

**Comment by dpelletier2017** [comment]
Hey no problem ;) 
I needed to do it in my upcoming game, and was surprised UIView.animateKeyFramesWithDuration wouldn't work. In fact I thought there was a bug where it would call the completion block right away.

So I managed to somewhat reproduce UIView.animateKeyFramesWithDuration in another way just to animate the rate. I learned a LOT of things doing that !

If you could just tell me the general steps required to update a framework in Xcode, I'd be glad to know ! I'm hitting my head on the wall right now for something that looks so simple to do 😫

Right now, what I do is : 
- Open the .xcworkspace file
- Do a couple of changes in the GaugeKit project on the left
- Build the GaugeKit framework on "Generic iOS Device"
- And then I expect it to work... :(

**Comment by dpelletier2017** [comment]
Colors array are now fully functional ! 
My UIColor Blender extension could use a little tweaking, but it's not bad.
Here's what a Circle Gauge gives when colorsArray = [UIColor.redColor(), UIColor.orangeColor(), UIColor.greenColor()]

[Animated Colors Array.mp4.zip](https://github.com/skywinder/GaugeKit/files/198947/Animated.Colors.Array.mp4.zip)

And you can put in as many colors as you want in the array :D

**Comment by skywinder** [comment]
@f8th  wow, pretty cool feature! :+1: 
I definitely want to add it also! But has a some additions, that want to add it before.
May I ask you to split this 2 thing on 2 PR's? I would like to review them separately.

And thank you for your contribution! I will try to make frameworks work by myself.Seems, that you are doing right. It should rebuild frameworks during your steps, I will check it now.
Did you try to "Delete Derived Data" in Xcode?

**Comment by dpelletier2017** [comment]
I don't have much time on my hands, but I'll try to separate them when I can. I tried deleting the cache, but nothing seems to work. It's not the only project that does this, I can't work with frameworks in Xcode for some reason, so I just copy the source files in my projects :-/

**Comment by sinanku** [comment]
This looks awesome, any update on when it will be merged?

**Comment by skywinder** [comment]
@f8th there was 3 problems:
1. you new method was not `public`, that's why it doesn's called properly
2. you send double instead CGFloat
3. Since you change Bool to [UIColor] - there was several conflicts in IB.

I already fixed everything. Please merge my PR and kindly check, that everything work. As soon as you check it - I will merge your update and will bump version! 👍

**Comment by sinanku** [comment]
@f8th this is a pretty useful tool I use for cleaning my workspace, in addition to deleting derived data whenever I have framework problems https://github.com/BendingSpoons/cocoapods-clean

Sometimes deleting the cache also helps ~/Library/Caches/com.apple.dt.Xcode

Also @skywinder is there any update on using gradients within the lines?https://github.com/skywinder/GaugeKit/issues/2

Great work on the library :)

**Comment by skywinder** [comment]
@f8th please merge my PR in order to fix errors: https://github.com/f8th/GaugeKit/pull/1

**Comment by dpelletier2017** [comment]
Should be fine !!! Great job

**Comment by skywinder** [comment]
Travis still fails, but it's something wrong with settings. Merged thanks!

**Pull request merged**
